package bankonet.Controller;

import bankonet.Entity.Client;
import bankonet.Repository.ClientRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/bankonet") // This means URL's start with /bankonet (after Application path)
public class ClientController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final ClientRepository clientRepository;

    @Autowired
    public ClientController(ClientRepository clientRepository) {
        this.clientRepository = clientRepository;
    }

    @GetMapping(path="/clients")
    public @ResponseBody Iterable<Client> getAllClients() {
        // This returns a JSON or XML with the users
        return clientRepository.findAll();
    }

    @PostMapping("/addClient")
    public @ResponseBody String addNewClient (@RequestParam String nom, @RequestParam String prenom) {

        Client n = new Client();
        n.setNom(nom);
        n.setPrenom(prenom);
        clientRepository.save(n);
        return "Saved";
    }

}

// java -jar target/gs-mysql-data-0.1.0.jar